---
app:
  id: mybot-1
  classpath:
    - /tmp

outputs:
  console:
    provider: healthcheckbot.outputs.ConsoleOutput
  gelf:
    provider: healthcheckbot.outputs.GelfOutput
    gelf_host: localhost
    gelf_port: 12201
    gelf_protocol: udp

triggers:
  each_1_minute:
    provider: healthcheckbot.triggers.SimpleTimer
    interval: 60

watchers:
  system_time:
    provider: healthcheckbot.watchers.SystemTimeWatcher
    triggers:
      - each_1_minute

  dns_doesnt_exist:
    provider: healthcheckbot.watchers.HttpRequest
    url: http://blahblah123blah.com/
    assert_response_time: 2
    assert_status: 200
    triggers:
      - each_1_minute

  google_home:
    provider: healthcheckbot.watchers.HttpRequest
    url: http://google.com
    assert_response_time: 3
    assert_status: 200
    triggers:
      - each_1_minute
    custom_assertions:
      check_title:
        provider: healthcheckbot.assertions.TitleAssert
        expected_title: 'Google'