---
name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be assigned for this release'
        required: true

jobs:
  run:
    name: Release a new version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: '${{ github.ref }}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Set new version
      run: |
        make set-version VERSION="${{ github.event.inputs.version }}"
    - name: Apply formatting, coppyright, lint
      run: make NO_VENV=True

    - name: Build packages
      run: make build NO_VENV=True

#    - name: Publish packages
#      run: make publish NO_VENV=True PYPI_API_KEY=${{ secrets.pypi_password }}

#    - uses: heinrichreimer/github-changelog-generator-action@v2.2
#      id: generate_changelog_file
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        output: CHANGELOG.md
#        futureRelease: v${{ github.event.inputs.version }}
#        unreleased: true
#        issues: true
##        addSections: '{ "notable-change": {"prefix": "**NotableChanges:**", "labels": ["notable-change"]} }'
#
#    - uses: heinrichreimer/github-changelog-generator-action@v2.2
#      id: generate_release_changelog
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        output: RELEASE_CHANGELOG.md
#        unreleasedOnly: true
#        issues: true
#        headerLabel: '## Changelog'
#        stripGeneratorNotice: true
#        stripHeaders: true
#        unreleasedLabel: ''
##        addSections: '{ "notable-change": {"prefix": "**NotableChanges:**", "labels": ["notable-change"]} }'
#
#    - name: Read Changelog
#      # This is a workaround for https://github.com/heinrichreimer/action-github-changelog-generator/issues/7
#      id: release_changelog
#      uses: juliangruber/read-file-action@v1
#      with:
#        path: ./RELEASE_CHANGELOG.md

    - name: Bump version
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Github Bot
        author_email: github@bot.com
        message: "Version bump and changelog update. New version is ${{ github.event.inputs.version }}"
        add: "./src/healthcheckbot/__version__.py CHANGELOG.md"
        push: true
        tag: "v${{ github.event.inputs.version }} --force"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge master -> stable
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: '${{ github.ref }}'
        target_branch: stable
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v${{ github.event.inputs.version }}'
        release_name: 'Version ${{ github.event.inputs.version }}'
        body: |
          ${{ steps.release_changelog.outputs.content }}
        draft: true
        prerelease: false